/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogs;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import utilities.DBConnection;
import ba.woodcraft.BA_Main;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import utilities.Utils;

/**
 *
 * @author Anonymous
 */
public class DlgRecords extends javax.swing.JFrame {

    public String rid;
    private Connection conn;
    private PreparedStatement pst;
    private ResultSet rs;
    private String idemp;
    private int iddar;
    private int idstage;
    private int idvar;
    private String check[] = new String[20];
    private String act = "";
    private String tblestages;
    private String tblquan;
    private String tblvar;
    private String tblwksrc;

    /**
     * Creates new form DlgRecords
     */
    public DlgRecords(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
        initComponents();
        setName();
        setStage(stagesjComboBox1);
        setStage(stagesjComboBox2);
        setVariety(varjComboBox1);
        setVariety(varjComboBox2);
        setpos();
//        for (int i = 0; i < 20; i++) {
//            this.check[i] = "";
//
//        }
//        DateFormat df = new SimpleDateFormat("MMM d, yyyy");
//        Date dateobj = dateoop.getDate();
//        df.format(dateobj);
        namejComboBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                setpos();
            }
        });

    }

    public void setpos() {
        try {
            conn = DBConnection.connectDb();
            String sql = "SELECT position from employee where name ='" + namejComboBox.getSelectedItem() + "'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {

                position.setText(rs.getString("position"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    public void setName() {
        try {
            String sql = "SELECT NAME FROM EMPLOYEE";
            conn = DBConnection.connectDb();
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("name");
                namejComboBox.addItem(name);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void setStage(JComboBox j) {
        try {
            String sql = "SELECT description FROM stages";
            conn = DBConnection.connectDb();
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("description");
                j.addItem(name);
                
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void setVariety(JComboBox j) {
        try {
            String sql = "SELECT description FROM varieties";
            conn = DBConnection.connectDb();
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("description");
                j.addItem(name);
              
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        periodjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tothjTextField = new javax.swing.JTextField();
        tghjTextField = new javax.swing.JTextField();
        weekjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dateoop = new com.toedter.calendar.JDateChooser();
        dayop = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namejComboBox = new javax.swing.JComboBox();
        position = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel87 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        consjTextField = new javax.swing.JTextField();
        obsjTextField = new javax.swing.JTextField();
        jCheckBox7 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        act6 = new javax.swing.JCheckBox();
        act3 = new javax.swing.JCheckBox();
        act5 = new javax.swing.JCheckBox();
        ac1 = new javax.swing.JCheckBox();
        act14 = new javax.swing.JTextField();
        act12 = new javax.swing.JTextField();
        act2 = new javax.swing.JCheckBox();
        act8 = new javax.swing.JCheckBox();
        act4 = new javax.swing.JCheckBox();
        act13 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        act10 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        act7 = new javax.swing.JCheckBox();
        act11 = new javax.swing.JTextField();
        act9 = new javax.swing.JCheckBox();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        quanjTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        wksrcjTextField = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        stagesjComboBox1 = new javax.swing.JComboBox();
        varjComboBox1 = new javax.swing.JComboBox();
        addjButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_pro = new javax.swing.JTable();
        deljButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        table_con = new javax.swing.JTable();
        stagesjComboBox2 = new javax.swing.JComboBox();
        addjButton1 = new javax.swing.JButton();
        varjComboBox2 = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        deljButton1 = new javax.swing.JButton();
        wksrcjTextField1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        quanjTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LABORATORY DAILY ACCOMPLISHMENT REPORT");
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"AWP", "ABSENT WITH PERMISSION"},
                {"AWOP", "ABSENT WITHOUT PERMISSION"},
                {"SL", "SICK LEAVE"},
                {"VL", "VACATION LEAVE"},
                {"OTHERS", "(JUSTIFY)"}
            },
            new String [] {
                "", ""
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Period:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Total OT Hours:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Day of Operation:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Date of Operation:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Week:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Total Reg. Hours:");

        dateoop.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateoopPropertyChange(evt);
            }
        });

        dayop.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(periodjTextField)
                    .addComponent(weekjTextField)
                    .addComponent(tghjTextField)
                    .addComponent(tothjTextField)
                    .addComponent(dateoop, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(dayop))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(dateoop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(periodjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(weekjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dayop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tghjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tothjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Operation Code:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Name:");

        namejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namejComboBoxActionPerformed(evt);
            }
        });

        position.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namejComboBox, 0, 222, Short.MAX_VALUE)
                    .addComponent(position))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(namejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBox8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox8.setText("Check and Inspect AGE in all stages of tissue cultures individually");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jLabel87.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel87.setText("Conclusions and Observations:");

        jLabel86.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel86.setText("Observations:");

        jCheckBox7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox7.setText("Check and Inspect Inocolator`s propagation proper handling");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCheckBox7)
                        .addGap(145, 145, 145)
                        .addComponent(jLabel86)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obsjTextField))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCheckBox8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel87)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consjTextField)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox7)
                    .addComponent(jLabel86)
                    .addComponent(obsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox8)
                    .addComponent(jLabel87)
                    .addComponent(consjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/save-png-image-4017.png"))); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        act6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        act6.setText("Prepare rubber bonds, clothe wipes for sterilization");
        act6.setToolTipText("");
        act6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                act6ActionPerformed(evt);
            }
        });

        act3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        act3.setText("1st. hr. sucker preperation");
        act3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                act3ActionPerformed(evt);
            }
        });

        act5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        act5.setText("Prepare envelop and bond papers, tissue papres for sterilization");
        act5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                act5ActionPerformed(evt);
            }
        });

        ac1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ac1.setText("Meeting");
        ac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ac1ActionPerformed(evt);
            }
        });

        act12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                act12ActionPerformed(evt);
            }
        });

        act2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        act2.setText("Clean sucker area & vicinity");
        act2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                act2ActionPerformed(evt);
            }
        });

        act8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        act8.setText("Clean, chopping area lavavo");
        act8.setToolTipText("");
        act8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                act8ActionPerformed(evt);
            }
        });

        act4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        act4.setText("Sucker soaking & disinfection");
        act4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                act4ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setText("From:");

        act10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        act10.setText("Clean & vacuum isolation room, culture room, media room, alley");
        act10.setToolTipText("");
        act10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                act10ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("ON UV:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("To:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("Times:");

        act7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        act7.setText("Prepare scalpel blade and Forceps for sterilization");
        act7.setToolTipText("");
        act7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                act7ActionPerformed(evt);
            }
        });

        act9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        act9.setText("Clean chamber, media and culture bottle, prior to propagation");
        act9.setToolTipText("");
        act9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                act9ActionPerformed(evt);
            }
        });

        jLabel88.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel88.setText("Open contaminated bottles:");

        jLabel89.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel89.setText("Clothes Changing from:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(act10)
                    .addComponent(act9)
                    .addComponent(act8)
                    .addComponent(act7)
                    .addComponent(act6)
                    .addComponent(act5)
                    .addComponent(ac1)
                    .addComponent(act2)
                    .addComponent(act3)
                    .addComponent(act4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel89, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel88, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(act13)
                                        .addComponent(act14, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(act11, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addComponent(act12)))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ac1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(act2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(act3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(act4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(act5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(act6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(act7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(act8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(act9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(act10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel88)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(act11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(act12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel89)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(act13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(act14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel2);

        jTabbedPane2.addTab("Activity", jScrollPane2);

        quanjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("VARIETY:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Quantity:");

        wksrcjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wksrcjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wksrcjTextFieldActionPerformed(evt);
            }
        });

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel83.setText("Please Indicate Quantity of propagated tissue culture:");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel41.setText("WK SOURCE:");

        stagesjComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                stagesjComboBox1PropertyChange(evt);
            }
        });

        addjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addjButton.setText("Add");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });

        table_pro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stages", "Quantity", "Variety", "WK Source"
            }
        ));
        table_pro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_proMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(table_pro);

        deljButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deljButton.setText("Delete");
        deljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deljButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel83)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(stagesjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quanjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wksrcjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deljButton)))
                        .addGap(52, 52, 52))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel83)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(quanjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel41)
                    .addComponent(wksrcjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stagesjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addjButton)
                    .addComponent(deljButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel4);

        jTabbedPane2.addTab("Propagated tissue culture", jScrollPane3);

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel84.setText("Please Indicate Quantity of USED bot and contaminated tissue culture  ");

        table_con.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stages", "Quantity", "Variety", "WK Source"
            }
        ));
        table_con.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_conMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(table_con);

        stagesjComboBox2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                stagesjComboBox2PropertyChange(evt);
            }
        });

        addjButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addjButton1.setText("Add");
        addjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButton1ActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setText("WK SOURCE:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Quantity:");

        deljButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deljButton1.setText("Delete");
        deljButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deljButton1ActionPerformed(evt);
            }
        });

        wksrcjTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wksrcjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wksrcjTextField1ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("VARIETY:");

        quanjTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel84)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(stagesjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quanjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wksrcjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deljButton1)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel84)
                .addGap(32, 32, 32)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(quanjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel42)
                    .addComponent(wksrcjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stagesjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addjButton1)
                    .addComponent(deljButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jPanel9);

        jTabbedPane2.addTab("USED bot and contaminated tissue culture", jScrollPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(645, 645, 645)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void act12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_act12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_act12ActionPerformed

    private void act2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_act2ActionPerformed
        // TODO add your handling code here:
        getCheckAct("Clean sucker area & vicinity");
    }//GEN-LAST:event_act2ActionPerformed

    private void act7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_act7ActionPerformed
        // TODO add your handling code here:
        getCheckAct(" Prepare scalpel blade and Forceps for sterilization");
    }//GEN-LAST:event_act7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (this.getTitle().equals("Update Records")) {
            try {

                Connection conn = DBConnection.connectDb();
                String sql = "UPDATE labdar SET week = '" + weekjTextField.getText() + "', period = '" + periodjTextField.getText()
                        + "'  WHERE ldar_id = '" + rid + "' ";
//                System.out.println(dayoopjComboBox.getSelectedItem());
                System.out.println(sql);
                Statement pst = conn.createStatement();
                pst.execute(sql);
                Utils.showMessage(this, "update");
                BA_Main.showRecords(BA_Main.tblList, BA_Main.QUERIES[5], "dar");

                this.setVisible(false);

            } catch (Exception e) {
                Utils.showMessage(this, "error");
            }
        } else {
            try {
                Connection conn = DBConnection.connectDb();
                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                Date dateobj = dateoop.getDate();

                System.out.println(df.format(dateobj));
                String sql = "SELECT employee_id from employee where name='" + namejComboBox.getSelectedItem().toString() + "' ";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                while (rs.next()) {

                    this.idemp = rs.getString("employee_id");
                }
//                System.out.println(df.format(dateoop.getDate()));
//                for(int j = 0 ; j < 20 ; j ++){
//                if(this.check[j]!=""){
//                
//                }
//                
//                }
                String sql1 = "INSERT INTO labdar(activities, date, employee_id,period,week, op_day,total_reg_hrs, total_ot_hrs, observation, conclusion) values('" + this.act + act11.getText() + act12.getText() + act13.getText() + act14.getText() + "', '" + df.format(dateobj) + "', '" + this.idemp + "',"
                        + "'" + periodjTextField.getText() + "', '" + weekjTextField.getText() + "', '" + dayop.getText() + "',"
                        + "'" + tghjTextField.getText() + "','" + tothjTextField.getText() + "','" + obsjTextField.getText() + "', '" + consjTextField.getText() + "')";
                System.out.println(sql1);
                Statement pst = conn.createStatement();
                pst.execute(sql1);

                getIddar();
//                getIdstage(stagesjComboBox1.getSelectedItem().toString());
//                getIdvar(varjComboBox1.getSelectedItem().toString());
                InsertPropagated(1,table_pro);
                 InsertPropagated(2, table_con);
                Utils.showMessage(this, "insert");
                BA_Main.showRecords(BA_Main.tblList, BA_Main.QUERIES[5], "labdar");

                this.setVisible(false);

            } catch (Exception e) {
                Utils.showMessage(this, "error");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    
    public void InsertPropagated(int ii, JTable t) {
        try {

            DefaultTableModel model = (DefaultTableModel) t.getModel();
            model.getRowCount();
            for (int i = 0; i < model.getRowCount(); i++) {

                getIdstage(model.getValueAt(i, 0).toString());
                System.out.println(model.getValueAt(i, 2).toString());
                getIdvar(model.getValueAt(i, 2).toString());

                String sql = "INSERT INTO qty_prop_or_cont(ldar_id, stage_id,var_id,week,qty,flag)"
                        + " VALUES(" + this.iddar + ", " + this.idstage + ", " + this.idvar + ", '" + model.getValueAt(i, 3).toString() + "','" + model.getValueAt(i, 1).toString() + "',"
                        + ii+")";
                Statement pst = conn.createStatement();
                pst.execute(sql);

            }

        } catch (Exception e) {
            e.printStackTrace();

        }

    }

    public void getCheckAct(String act) {
        try {
            this.act = this.act + act;

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void getIdstage(String stagedes) {
        try {
            String sql = "SELECT stage_id from stages where description = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, stagedes);
            rs = pst.executeQuery();
            while (rs.next()) {

                this.idstage = rs.getInt("stage_id");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void getIddar() {
        try {
            String sql = "SELECT max(ldar_id) as 'max' from labdar ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {

                this.iddar = rs.getInt("max");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void getIdvar(String idvar) {
        try {
            String sql = "SELECT var_id from varieties where description = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, idvar);
            rs = pst.executeQuery();
            while (rs.next()) {

                this.idvar = rs.getInt("var_id");
            }

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    private void ac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ac1ActionPerformed
        // TODO add your handling code here:
        getCheckAct("Meeting");

    }//GEN-LAST:event_ac1ActionPerformed

    private void act3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_act3ActionPerformed
        // TODO add your handling code here:
        getCheckAct("1st. hr. sucker preperation");
    }//GEN-LAST:event_act3ActionPerformed

    private void act4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_act4ActionPerformed
        // TODO add your handling code here:
        getCheckAct("Sucker soaking & disinfection");
    }//GEN-LAST:event_act4ActionPerformed

    private void act5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_act5ActionPerformed
        // TODO add your handling code here:
        getCheckAct("Prepare envelop and bond papers, tissue papres for sterilization");
    }//GEN-LAST:event_act5ActionPerformed

    private void act6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_act6ActionPerformed
        // TODO add your handling code here:
        getCheckAct("Prepare rubber bonds, clothe wipes for sterilization");
    }//GEN-LAST:event_act6ActionPerformed

    private void act8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_act8ActionPerformed
        // TODO add your handling code here:
        getCheckAct("Clean, chopping area lavavo");
    }//GEN-LAST:event_act8ActionPerformed

    private void act9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_act9ActionPerformed
        // TODO add your handling code here:
        getCheckAct("Clean chamber, media and culture bottle, prior to propagation");
    }//GEN-LAST:event_act9ActionPerformed

    private void act10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_act10ActionPerformed
        // TODO add your handling code here:
        getCheckAct("Clean & vacuum isolation room, culture room, media room, alley");
    }//GEN-LAST:event_act10ActionPerformed

    private void namejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namejComboBoxActionPerformed

    private void wksrcjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wksrcjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wksrcjTextFieldActionPerformed

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_pro.getModel();
        System.out.println(model.getRowCount());
        Object[] row = new Object[4];
        for (int i = 0; i < 1; i++) {

            row[0] = stagesjComboBox1.getSelectedItem().toString();
            row[1] = quanjTextField.getText();
            row[2] = varjComboBox1.getSelectedItem().toString();
            row[3] = wksrcjTextField.getText();

            model.addRow(row);

        }
    }//GEN-LAST:event_addjButtonActionPerformed

    private void table_proMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_proMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_table_proMouseClicked

    private void deljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deljButtonActionPerformed
        // TODO add your handling code here:
        int i = table_pro.getSelectedRow();
        DefaultTableModel n = (DefaultTableModel) table_pro.getModel();
        n.removeRow(i);


    }//GEN-LAST:event_deljButtonActionPerformed

    private void stagesjComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_stagesjComboBox1PropertyChange
// getIddar();
//        System.out.println(this.iddar);
    }//GEN-LAST:event_stagesjComboBox1PropertyChange

    private void dateoopPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateoopPropertyChange
        // TODO add your handling code here:
        if (evt.getPropertyName().equals("date")) {
            Date opdate = dateoop.getDate();
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("EEEE");
            dayop.setText(simpleDateFormat.format(opdate));
        }
    }//GEN-LAST:event_dateoopPropertyChange

    private void table_conMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_conMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_conMouseClicked

    private void stagesjComboBox2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_stagesjComboBox2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_stagesjComboBox2PropertyChange

    private void addjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButton1ActionPerformed
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel) table_con.getModel();
        System.out.println(model.getRowCount());
        Object[] row = new Object[4];
        for (int i = 0; i < 1; i++) {

            row[0] = stagesjComboBox2.getSelectedItem().toString();
            row[1] = quanjTextField1.getText();
            row[2] = varjComboBox2.getSelectedItem().toString();
            row[3] = wksrcjTextField1.getText();

            model.addRow(row);

        }
    }//GEN-LAST:event_addjButton1ActionPerformed

    private void deljButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deljButton1ActionPerformed
        // TODO add your handling code here:
        int i = table_con.getSelectedRow();
        DefaultTableModel n = (DefaultTableModel) table_con.getModel();
        n.removeRow(i);
    }//GEN-LAST:event_deljButton1ActionPerformed

    private void wksrcjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wksrcjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wksrcjTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new DlgRecords().setVisible(true);
                DlgRecords dialog = new DlgRecords(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox ac1;
    private javax.swing.JCheckBox act10;
    private javax.swing.JTextField act11;
    private javax.swing.JTextField act12;
    private javax.swing.JTextField act13;
    private javax.swing.JTextField act14;
    private javax.swing.JCheckBox act2;
    private javax.swing.JCheckBox act3;
    private javax.swing.JCheckBox act4;
    private javax.swing.JCheckBox act5;
    private javax.swing.JCheckBox act6;
    private javax.swing.JCheckBox act7;
    private javax.swing.JCheckBox act8;
    private javax.swing.JCheckBox act9;
    private javax.swing.JButton addjButton;
    private javax.swing.JButton addjButton1;
    private javax.swing.JTextField consjTextField;
    public com.toedter.calendar.JDateChooser dateoop;
    private javax.swing.JTextField dayop;
    private javax.swing.JButton deljButton;
    private javax.swing.JButton deljButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JComboBox namejComboBox;
    private javax.swing.JTextField obsjTextField;
    public javax.swing.JTextField periodjTextField;
    private javax.swing.JTextField position;
    private javax.swing.JTextField quanjTextField;
    private javax.swing.JTextField quanjTextField1;
    private javax.swing.JComboBox stagesjComboBox1;
    private javax.swing.JComboBox stagesjComboBox2;
    private javax.swing.JTable table_con;
    private javax.swing.JTable table_pro;
    public javax.swing.JTextField tghjTextField;
    public javax.swing.JTextField tothjTextField;
    private javax.swing.JComboBox varjComboBox1;
    private javax.swing.JComboBox varjComboBox2;
    public javax.swing.JTextField weekjTextField;
    private javax.swing.JTextField wksrcjTextField;
    private javax.swing.JTextField wksrcjTextField1;
    // End of variables declaration//GEN-END:variables
}
